### ISSUE TITLE
Logging error when some games were skipped

### ISSUE THREAD

**Issue by AxelTerizaki** [michael-n0813/linux-idle-master#19]
Hello :)

When skipping some games and idle-master completes, it prints out an error upon exiting.

Not a big issue since the script finished gathering all cards, but... :)

```
Traceback (most recent call last):
  File "/home/aterizak/dev/linux-idle-master/./start.py", line 359, in <module>
    logging.warning(Fore.YELLOW + numSkip + " games skipped" + Fore.RESET)
                    ~~~~~~~~~~~~^~~~~~~~~
TypeError: can only concatenate str (not "int") to str
```

**Comment by michael-n0813** [comment]
Thanks, fixed.  :)
https://github.com/michael-n0813/linux-idle-master/commit/916ef3e442b34fc25e1c012922a7eee091b26568


Happy new year in 2024!
