### ISSUE TITLE
sort = "mostvalue" can't be used in settings.txt

### ISSUE THREAD

**Issue by Saroumane** [michael-n0813/linux-idle-master#7]
the setting `sort = "mostvalue"`
can't be used anymore in `settings.txt `, as the URL used to check prices "https://api.enhancedsteam.com/" seems to be KO.
Maybe this site https://steam.tools/cards/  could be used instead. (Sorry, can't do it myself)

**Comment by michael-n0813** [comment]
Thanks for letting me know, as of now I won't be updating or fixing this issue as I don't want to incorporate some other site or API only for it to close down or change their code.

**Comment by michael-n0813** [comment]
Hey,

I have updated the API so it should work now, if anything is wrong you can start a new issue.

**Comment by Saroumane** [comment]
Hi, thanks for fixing this. I confirm it works again.
