### ISSUE TITLE
steamLoginSecure should be used instead of steamLogin in start.py

### ISSUE THREAD

**Issue by Saroumane** [michael-n0813/linux-idle-master#8]
`start.py ` can not work 'as is' : Steam has removed steamLogin value in cookies, only **steamLoginSecure** should be used.

**Comment by Saroumane** [comment]
#9 #9

**Comment by michael-n0813** [comment]
The script uses steamLoginSecure cookie data

> then copy steamLoginSecure Content (really long alpha-numerical code) from cookie into the second field in settings.txt

I might make the setting.txt file to reflect this by renaming "steamLogin" to "steamLoginSecure" to not cause confusion.
